# Simple colcon build and deploy
version: 2.1

executors:
  simple-docker:
    docker:
      - image: gallaisoma/ros2-foxy:latest
    working_directory: ~/workspace/src/navigation2

jobs:
  build:
    executor: simple-docker
    steps:
      - checkout:
          path: ~/workspace/src/navigation2
      - run: 
          name: Run build
          command: |
            cd ../..
            pwd
            ls
            source /opt/ros/foxy/setup.bash
            apt-get update
            rosdep init 
            rosdep update
            rosdep install -y -r -q --from-paths src --ignore-src --rosdistro foxy
            colcon build 

      - persist_to_workspace:
          root: ../ 
          paths: 
            - .
  deploy:
    executor: simple-docker
    steps: 
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Deploy the deb artifact
          command: |
            cd ../..
            pwd
            ls
            source ~/workspace/install/setup.bash
            pip install -U bloom
            apt update
            apt install -y fakeroot
            rosdep init
            rosdep update
            bloom-generate rosdebian
            apt install -y dpkg-dev debhelper
            fakeroot debian/rules binary
            cd ..
            mv ros-foxy-navigation2_* ros-foxy-navigation2.deb

      - store_artifacts:
          path: ~/workspace/ros-foxy-navigation2.deb


workflows:
  build and test:
    jobs:
      - build
      - deploy:
          requires:
            - build
